notes_app/urls.py
from django.contrib import admin
from django.urls import path
from users.views import LoginView
from main.views import (
    HomeView,
    CreateFlashDeckView,
    CreateCollectionView,
    CollectionDetailView,
    DeleteFlashCard,
    ViewFlashCardDeck,
    DeleteFlashCardDeck,
    PracticeFlashcards,
    DeleteCollectionView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LoginView.as_view(), name="login"),
    path("home/", HomeView.as_view(), name="home"),
    path("create_collection", CreateCollectionView.as_view(), name="create-collection"),
    path(
        "delete_collection/<int:pk>",
        DeleteCollectionView.as_view(),
        name="delete-collection",
    ),
    path(
        "collection/<int:collection_id>/create",
        CreateFlashDeckView.as_view(),
        name="create",
    ),
    path(
        "collection/<int:collection_id>",
        CollectionDetailView.as_view(),
        name="collection-detail",
    ),
    path(
        "collection/<int:collection_id>/flashcards/<int:deck_id>",
        ViewFlashCardDeck.as_view(),
        name="collection-view-flashcards",
    ),
    path(
        "collection/<int:collection_id>/flashcards/<int:deck_id>/practice",
        PracticeFlashcards.as_view(),
        name="collection-practice-flashcards",
    ),
    path(
        "collection/<int:collection_id>/flashcards/<int:deck_id>/delete",
        DeleteFlashCardDeck.as_view(),
        name="collection-delete-deck",
    ),
    path("delete_flashcard", DeleteFlashCard.as_view(), name="delete-flashcard"),
]

main/models.py
from django.db import models
from users.models import User


class FlashCardCollection(models.Model):
    """
    Collection of FlashCardDecks. Can have many FlashCardDeck objects
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now=True)


class FlashCardDeck(models.Model):
    """
    FlashCardDeck which contains FlashCards and belongs to a FlashCardCollection
    """

    name = models.CharField(max_length=256)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now=True)
    collection = models.ForeignKey(FlashCardCollection, on_delete=models.CASCADE, null=True)


class FlashCard(models.Model):
    """
    FlashCard that is the basic unit of learning for the flashcard app
    """

    deck = models.ForeignKey(FlashCardDeck, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField()

main/forms.py
from django import forms
from django.forms import formset_factory
from .models import FlashCard, FlashCardCollection, FlashCardDeck


class CollectionForm(forms.ModelForm):
    """
    Form for creating a new FlashCardCollection object
    """

    class Meta:
        model = FlashCardCollection
        fields = ["name", "description"]

    def __init__(self, *args, **kwargs):
        super(CollectionForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["class"] = "form-control"


class FlashCardDeckForm(forms.ModelForm):
    """
    Form for creating a new FlashCardDeck
    """

    class Meta:
        model = FlashCardDeck
        fields = ["name", "description"]

    def __init__(self, *args, **kwargs):
        super(FlashCardDeckForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["class"] = "form-control"


class FlashCardForm(forms.ModelForm):
    """
    Form for creating a new FlashCard. Used as a formset
    to create multiple.
    """

    class Meta:
        model = FlashCard
        fields = ["question", "answer"]


FlashCardFormset = formset_factory(FlashCardForm, max_num=100, extra=0)

main/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import FlashCardFormset, CollectionForm, FlashCardDeckForm
from .models import FlashCard, FlashCardDeck, FlashCardCollection


class HomeView(LoginRequiredMixin, View):
    template_name = "main/home.html"

    def get(self, request, *args, **kwargs):
        """
        Return overview of FlashCardCollection objects. First view after login.
        """
        context = {"collections": FlashCardCollection.objects.filter(user=request.user)}
        return render(request, self.template_name, context)


class CollectionDetailView(LoginRequiredMixin, View):
    template_name = "main/collection_detail.html"

    def get(self, request, *args, **kwargs):
        """
        Shows the FlashCardDeck objects in a FlashCardCollection
        """
        collection_id = kwargs["collection_id"]
        flashcard_decks = FlashCardDeck.objects.filter(
            collection_id=collection_id, collection__user=request.user
        )
        for deck in flashcard_decks:
            deck.count = FlashCard.objects.filter(deck=deck).count()

        context = {
            "collection": FlashCardCollection.objects.get(id=collection_id),
            "flashcard_decks": flashcard_decks,
        }
        return render(request, self.template_name, context)


class CreateCollectionView(LoginRequiredMixin, View):
    template_name = "main/create_collection.html"
    form = CollectionForm

    def get(self, request, *args, **kwargs):
        """
        Returns the form to create a FlashCardCollection
        """
        context = {"form": self.form()}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Validates the FlashCardCollectionForm and creates a new FlashCardCollection
        """
        form = self.form(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect("home")
        else:
            context = {"form": form}
            return render(request, self.template_name, context)


class DeleteCollectionView(View):
    def post(self, request, *args, **kwargs):
        FlashCardCollection.objects.get(id=kwargs["pk"]).delete()
        return redirect("home")


class CreateFlashDeckView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = "main/create_deck.html"

    def get(self, request, *args, **kwargs):
        """
        View for adding new flashcards to a FlashCardDeck
        """
        context = {
            "form": FlashCardDeckForm(),
            "formset": FlashCardFormset(),
            "collection": FlashCardCollection.objects.get(id=kwargs["collection_id"]),
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Processes the new flashcards
        """
        form = FlashCardDeckForm(request.POST)
        if form.is_valid():
            deck = form.save(commit=False)
            deck.collection_id = kwargs["collection_id"]
            deck.save()
            return redirect("collection-detail", collection_id=kwargs["collection_id"])
        else:
            context = {
                "form": form,
            }
            return render(request, self.template_name, context)

    def test_func(self):
        """
        Checks whether the FlashCardCollection belongs to the user that is request it.
        """
        collection = FlashCardCollection.objects.get(id=self.kwargs["collection_id"])
        if collection.user == self.request.user:
            return True
        else:
            return False


class ViewFlashCardDeck(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = "main/flashcard_deck.html"

    def get(self, request, *args, **kwargs):
        """
        View a FlashCardDeck and its related FlashCard objects
        """
        deck_id = kwargs["deck_id"]
        deck = FlashCardDeck.objects.get(id=deck_id)
        flashcards = FlashCard.objects.filter(deck=deck)
        context = {
            "deck": deck,
            "flashcards": flashcards,
            "formset": FlashCardFormset(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Processes new flashcards
        """
        deck_id = kwargs["deck_id"]
        deck = FlashCardDeck.objects.get(id=deck_id)
        formset = FlashCardFormset(request.POST)

        if formset.is_valid():
            new_flashcards = []
            for form in formset:
                new_card = FlashCard(
                    deck=deck,
                    question=form.cleaned_data["question"],
                    answer=form.cleaned_data["answer"],
                )
                new_flashcards.append(new_card)
            FlashCard.objects.bulk_create(new_flashcards)

        context = {
            "deck": deck,
            "flashcards": FlashCard.objects.filter(deck=deck),
            "formset": FlashCardFormset(),
        }
        return render(request, self.template_name, context)

    def test_func(self):
        """
        Checks whether the FlashCardDeck belongs to the logged in user
        """
        deck_id = self.kwargs["deck_id"]
        deck = FlashCardDeck.objects.get(id=deck_id)
        if deck.collection.user == self.request.user:
            return True
        else:
            False


class DeleteFlashCard(LoginRequiredMixin, UserPassesTestMixin, View):
    def post(self, request, *args, **kwargs):
        """
        Deletes a FlashCard
        """
        FlashCard.objects.get(id=request.POST["flashcard_id"]).delete()
        return HttpResponse("OK")

    def test_func(self):
        """
        Checks whether the FlashCard object belongs to the logged in user
        """
        flashcard_id = self.request.POST["flashcard_id"]
        flashcard = FlashCard.objects.get(id=flashcard_id)
        if flashcard.deck.collection.user == self.request.user:
            return True
        else:
            return False


class DeleteFlashCardDeck(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        """
        Deletes a FlashCardDeck
        """
        deck_id = kwargs["deck_id"]
        FlashCard.objects.filter(deck_id=deck_id).delete()
        FlashCardDeck.objects.get(id=deck_id).delete()
        redirect("collection-view-flashcards", collection_id=kwargs["collection_id"])

    def test_func(self):
        """
        Checks whether the FlashCardDeck belongs to the logged in user
        """
        deck = FlashCardDeck.objects.get(id=self.kwargs["deck_id"])
        if deck.collection.user == self.request.user:
            return True
        else:
            return False


class PracticeFlashcards(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = "main/practice_flashcards.html"

    def get(self, request, *args, **kwargs):
        """
        Returns a random flashcard
        """
        deck_id = kwargs["deck_id"]
        deck = FlashCardDeck.objects.get(id=deck_id)
        flashcard = FlashCard.objects.filter(deck=deck).order_by("?").first()

        context = {"card": flashcard, "deck": deck}
        return render(request, self.template_name, context)

    def test_func(self):
        """
        Checks whether the FlashCardDeck belongs to the logged in user.
        """
        deck = FlashCardDeck.objects.get(id=self.kwargs["deck_id"])
        if deck.collection.user == self.request.user:
            return True
        else:
            return False

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    {% load static %}
    <meta charset="utf-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
</head>
<body>
    {% block content %}

    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    {% block script_tags %}

    {% endblock %}
</body>
</html>

main/templates/main/collection_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <a href="{% url 'home' %}">Back to home</a>
    <h1>{{ collection.name }}</h1>
    <p>Date created: {{ collection.date_created }}</p>
    <p>Description: {{ collection.description }}</p>
    <p>Below are the flashcard decks for this collection</p>
    <a href="{% url 'create' collection_id=collection.id %}" class="btn btn-primary">Create new flashcard deck</a>
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Date Created</th>
            <th>Count</th>
            <th>Actions</th>
        </thead>
        <tbody>
            {% for deck in flashcard_decks %}
            <tr>
                <td>{{ deck.name }}</td>
                <td>{{ deck.date_created }}</td>
                <td>{{ deck.count }}</td>
                <td>
                    <a href="{% url 'collection-view-flashcards' collection_id=collection.id deck_id=deck.id %}" class="viewlink">View</a>,
                    <a href="{% url 'collection-practice-flashcards' collection_id=collection.id deck_id=deck.id %}" class="link-primary">Practice</a>,
                    <a href="{% url 'collection-delete-deck' collection_id=collection.id deck_id=deck.id %}" class="link-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

main/templates/main/create_collection.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <a href="{% url 'home' %}">Back to home</a>
    <h1>Create collection</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    </div>
{% endblock content %}

main/templates/main/create_deck.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <a href="{% url 'home' %}">Back to home</a>
    <h1>Create flashcard deck</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock content %}

main/templates/main/create_flashcards.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h1>Create a new deck of flashcards</h1>
<div class="main container">
    <a href="{% url 'collection-detail' collection_id=collection.id %}">Back to collection</a>
    <div class="row">
        <form method="post" class="col" id="flashcards">
            <label for="id_name">Flashcard Deck Name</label>
            {{ form.name }}
            <label for="id_description">Description</label>
            {{ form.description }}
            <div id="cards-container">
                {% csrf_token %}
                {{ formset.management_form }}
                {% include 'main/new_flashcard.html' %}
                {% include 'main/new_flashcard.html' %}
            </div>
            <button class="btn btn-primary btn-add" type="submit">Save</button>
            <a class="btn btn-primary btn-add" onclick="addEditorRow();">Add row</a>
        </form>

    </div>
</div>
<script>
    const new_row_url = "{% url 'new-row' %}"
</script>
<script src="{% static 'build/ckeditor.js' %}"></script>
<script src="{% static 'js/main/create_flashcards.js' %}"></script>
{% endblock content %}

main/templates/main/flashcard_deck.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <a href="{% url 'collection-detail' collection_id=deck.collection.id %}" class="link-primary">Back to collection</a>
    <h1>Flashcard deck: {{ deck.name }}</h1>
    <form id="id_flashcard_form" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% if not flashcards %}
            <p class="badge text-bg-primary">No flashcards created yet</p>
        {% endif %}
        <div id="flashcard-container">
            {% for flashcard in flashcards %}
                <div class="row mb-3">
                    <div class="col card me-3 mb-3 shadow">{{ flashcard.question|safe }}</div>
                    <div class="col card mb-3 shadow">{{ flashcard.answer|safe }}</div>
                    <div>
                        <a
                            class="btn btn-outline-danger delete-button"
                            onclick="deleteExistingFlashcard(this, {{ flashcard.id }})"
                        >Delete</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div>
            <button type="button" class="btn btn-primary" onclick="addRow();">Add row</button>
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </form>

</div>
{% endblock content %}
{% block script_tags %}
    <script>
        const csrfmiddlewaretoken = "{{ csrf_token }}";
        const url_delete_flashcard = "{% url 'delete-flashcard' %}";
    </script>
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="{% static 'js/main/create_flashcards.js' %}"></script>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Collections</h1>
    <a href="{% url 'create-collection' %}" class="btn btn-primary">Create new collection</a>
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Date Created</th>
            <th>Actions</th>
        </thead>
        <tbody>
            {% for collection in collections %}
            <tr>
                <td>{{ collection.name }}</td>
                <td>{{ collection.date_created }}</td>
                <td class="d-flex">
                    <a href="{% url 'collection-detail' collection_id=collection.id %}" class="viewlink">View</a>,
                    <form id="id_delete_{{ collection.id }}" method="post" action="{% url 'delete-collection' pk=collection.id %}">
                        <a
                            href="javascript:{}"
                            onclick="document.getElementById('id_delete_{{ collection.id }}').submit()"
                            class="link-danger ms-1"
                        >Delete</a>
                        {% csrf_token %}
                        <input type="submit" value="DELETE" hidden>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

main/templates/main/new_flashcard.html
<div class="row mb-3 flashcard-row">
    <div class="col-6">
        <textarea name="form-0-question" class="editor question-editor" id="id_form-0-question">

        </textarea>
    </div>
    <div class="col-6">
        <textarea name="form-0-answer" class="editor answer-editor" id="id_form-0-answer">

        </textarea>
    </div>
</div>
<hr>

main/templates/main/practice_flashcards.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h1>Practice</h1>
<a href="{% url 'collection-detail' collection_id=deck.collection.id %}" class="link-primary">Back to collection</a>
<div id="id_question" class="card shadow mb-3">{{ card.question|safe }}</div>
<div id="id_answer" class="card shadow mb-3" hidden>{{ card.answer|safe }}</div>
<button id="id_show_answer" class="btn btn-primary">Show answer</button>
<a href="{% url 'collection-practice-flashcards' collection_id=deck.collection.id deck_id=deck.id %}" id="id_next_question" class="btn btn-primary" hidden>Next question</a>
<script src="{% static 'js/main/practice_flashcards.js' %}"></script>
{% endblock content %}